FROM python:3.13.7

WORKDIR /photo-bucket-fastapi

COPY requirements-dev.txt requirements.txt ./
RUN pip install --no-cache-dir -r requirements-dev.txt

COPY . .

CMD ["fastapi", "dev", "app/main.py", "--port", "80", "--host", "0.0.0.0"]