"""is_deleted column added to Photo table

Revision ID: 37f8b1c264e6
Revises: 57974575112a
Create Date: 2025-12-05 18:19:30.956943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37f8b1c264e6'
down_revision: Union[str, Sequence[str], None] = '57974575112a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'is_deleted')
    # ### end Alembic commands ###
