"""s3_key column added

Revision ID: 0a83d0e2059a
Revises: 37f8b1c264e6
Create Date: 2025-12-18 01:38:55.792468

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0a83d0e2059a"
down_revision: Union[str, Sequence[str], None] = "37f8b1c264e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "photo",
        sa.Column(
            "s3_key",
            sa.String(length=256),
            nullable=False,
            server_default="placeholder",
        ),
    )
    # Remove server default after migration completes if you don't want it permanently
    op.alter_column("photo", "s3_key", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("photo", "s3_key")
    # ### end Alembic commands ###
